- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.task
(
    title character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date date,
    due_date date,
    status boolean NOT NULL,
    code integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    main_task integer,
    user_email character varying COLLATE pg_catalog."default",
    CONSTRAINT task_pkey PRIMARY KEY (code)
);

COMMENT ON TABLE public.task
    IS 'This is a task created by a user';

COMMENT ON COLUMN public.task.title
    IS 'Task title';

COMMENT ON COLUMN public.task.description
    IS 'Task description (optional)';

COMMENT ON COLUMN public.task.start_date
    IS 'Date where the task begins (optional)';

COMMENT ON COLUMN public.task.due_date
    IS 'Date where the task finishes (optional)';

COMMENT ON COLUMN public.task.status
    IS 'task status (Done or not done / true or false)';

COMMENT ON COLUMN public.task.code
    IS 'Task unique code';

COMMENT ON COLUMN public.task.main_task
    IS 'This points to the main task code, a task can perform multiple subtasks';

COMMENT ON COLUMN public.task.user_email
    IS 'This points to the user''s email who created the task';

CREATE TABLE IF NOT EXISTS public."user"
(
    email character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default" NOT NULL,
    last_name character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (email)
);

COMMENT ON TABLE public."user"
    IS 'This is a user from the app';

COMMENT ON COLUMN public."user".email
    IS 'The user''s unique email used to log in into the service';

COMMENT ON COLUMN public."user".first_name
    IS 'The user''s first name (Mandatory)';

COMMENT ON COLUMN public."user".last_name
    IS 'The user''s last name (optional)';

COMMENT ON COLUMN public."user".password
    IS 'The user''s hashed password';

ALTER TABLE IF EXISTS public.task
    ADD CONSTRAINT main_task_fk FOREIGN KEY (main_task)
    REFERENCES public.task (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMENT ON CONSTRAINT main_task_fk ON public.task
    IS 'This points to the main task code';



ALTER TABLE IF EXISTS public.task
    ADD CONSTRAINT user_email_fk FOREIGN KEY (user_email)
    REFERENCES public."user" (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMENT ON CONSTRAINT user_email_fk ON public.task
    IS 'This points to the user''s primary key';


END;